language: go
gobuild_args: -v -tags ci
dist: precise
sudo: required

os:
  - linux
  - osx

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  global:
    GO111MODULE=on

before_install:
  - ./admin/setup_minio_test_environment.sh
  - ./admin/setup_pureftpd_test_environment.sh
  - if [[ $TRAVIS_GO_VERSION == 1.13* ]]; then go get github.com/axw/gocov/gocov github.com/modocache/gover github.com/mattn/goveralls; fi

script:
  - go test -v -tags ci ./...
  - if [[ $TRAVIS_GO_VERSION == 1.13* ]]; then $GOPATH/bin/goveralls -service=travis-ci; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/00060e9fbbd266eedf3b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

  email:
    on_success: change
    on_failure: always
